In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Tensors

## Creating tensors

In [2]:
# scalar - only value no dimension
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim,scalar.item()

(0, 7)

In [4]:
# vector - value and dimensions
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [5]:
vector.ndim,vector.shape

(1, torch.Size([2]))

In [6]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 8]]);
MATRIX

tensor([[7, 8],
        [9, 8]])

In [7]:
MATRIX.ndim,MATRIX[0],MATRIX[1]

(2, tensor([7, 8]), tensor([9, 8]))

In [8]:
# TENSOR
TENSOR = torch.tensor([
	[
		[1, 2, 3, 5],
		[4, 5, 6, 5],
		[7, 8, 9, 5]
	],
	[
		[1, 2, 3, 4],
		[1, 2, 3, 4],
		[1, 2, 3, 4]
	]
])
TENSOR

tensor([[[1, 2, 3, 5],
         [4, 5, 6, 5],
         [7, 8, 9, 5]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]])

In [9]:
TENSOR.ndim,TENSOR.shape

(3, torch.Size([2, 3, 4]))

In [10]:
# random tensors
random_tensor = torch.rand(5, 3, 5)
random_tensor

tensor([[[0.9754, 0.5037, 0.7296, 0.3010, 0.9955],
         [0.5259, 0.5428, 0.6620, 0.5682, 0.9827],
         [0.1619, 0.1036, 0.4620, 0.3985, 0.5924]],

        [[0.0481, 0.1711, 0.4629, 0.0674, 0.5111],
         [0.3506, 0.5170, 0.4742, 0.3074, 0.1925],
         [0.3416, 0.9122, 0.6352, 0.9611, 0.1361]],

        [[0.3470, 0.2106, 0.2358, 0.2969, 0.1945],
         [0.7305, 0.6752, 0.9922, 0.2959, 0.2600],
         [0.7214, 0.3136, 0.5026, 0.3049, 0.8542]],

        [[0.8082, 0.5551, 0.0247, 0.5471, 0.6774],
         [0.4690, 0.0323, 0.4371, 0.7597, 0.0426],
         [0.0246, 0.6625, 0.5200, 0.0093, 0.6304]],

        [[0.1389, 0.8548, 0.0492, 0.5504, 0.0650],
         [0.9782, 0.1472, 0.8234, 0.5267, 0.2710],
         [0.7173, 0.4822, 0.0078, 0.5186, 0.8962]]])

In [11]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (r,g,b) is a common way to represent images
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [12]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
zeros,ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [13]:
ones.dtype # datatype of your tensor

torch.float32

## Creating a range of tensors and tensor-likes

In [14]:
# Use torch.range
one_to_ten = torch.arange(start=1, end=1000, step=77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [15]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [16]:
# float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16, device="cuda", requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [17]:
float_32_tensor = float_16_tensor.type(torch.float32)
float_32_tensor.dtype,float_16_tensor.dtype

(torch.float32, torch.float16)

## Manipulating Tensors

Tensor operations include:
- Addition
- Subtraction
- Multiplcation (element-wise)
- Division 
- Matrix multiplication / Dot product

In [18]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [19]:
tensor + 10,tensor - 10,tensor * 10,tensor / 10 # using python operations

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [20]:
torch.add(tensor, 10),torch.subtract(tensor, 10),torch.mul(tensor, 10),torch.div(tensor, 10) # using pytorch methods

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [21]:
# Element wise multiplcation
tensor * tensor

tensor([1, 4, 9])

In [22]:
torch.matmul(tensor, tensor),tensor @ tensor

(tensor(14), tensor(14))

In [23]:
torch.mm(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A *transpose* switches the axes of a given tensor.

In [ ]:
tensor_T = torch.rand(3, 2)
tensor_T,tensor_T.shape,tensor_T.T,tensor_T.T.shape

(tensor([[0.7343, 0.2180],
         [0.5796, 0.5222],
         [0.0671, 0.5936]]),
 torch.Size([3, 2]),
 tensor([[0.7343, 0.5796, 0.0671],
         [0.2180, 0.5222, 0.5936]]),
 torch.Size([2, 3]))

In [ ]:
torch.mm(torch.rand(3, 2), torch.rand(3, 2).T) # transposed second tensor

tensor([[0.8159, 0.8781, 0.6312],
        [0.5194, 0.4228, 0.3550],
        [0.4796, 0.4376, 0.3440]])

In [ ]:
torch.mm(torch.rand(3, 2).T, torch.rand(3, 2)) # transposed first tensor

tensor([[0.1115, 0.5650],
        [0.1476, 1.1855]])

## Tensor Aggregation

Finding the min, max, mean, sum, etc

In [ ]:
x = torch.arange(0, 100, 10, type=torch.float32)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x),torch.min(x)

(tensor(90), tensor(0))

In [ ]:
torch.mean(x, dtype=torch.float32)

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

- Reshaping: reshapes an input tensor to a defined shape
- View: Returns a view of an input tensor of a certain shape but keep the same memory as the original tensor
- Stacking: Combine multiple tensors on top of each other (vstack) or next to each other (hstack) or simply just stack on various dimensions using `torch.stack`
- Squeeze: Removes all `1` dimensions from a tensor
- Unsqueeze: add a `1` dimension to a target tensor
- Permute: Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
y = torch.arange(1., 10.)
y,y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
y, y.shape, y.reshape(9, 1), y.reshape(9, 1).shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
y.view(1, 9),y.view(1, 9).shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
torch.stack([y, y], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
z = torch.zeros(size=(3, 1))
z,z.shape,torch.squeeze(z),torch.squeeze(z).shape

(tensor([[0.],
         [0.],
         [0.]]),
 torch.Size([3, 1]),
 tensor([0., 0., 0.]),
 torch.Size([3]))

In [ ]:
w = torch.rand(size=(224, 224, 3)) # image dimensions [height, width, color_channels]
w_permuted = w.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0
w.shape,w_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x,x[0],x[0][0],x[0][0][0]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
x, x[:], x[:, 0], x[:, :, 0]

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3]]),
 tensor([[1, 4, 7]]))