# Reproducibility

"Trying to take the random out of random" - Daniel Bourke / FreeCodeCamp


`start with random numbers -> tensor operations -> update random numbers to try and make them better represenations of the data -> repeat -> repeat ...`

Using a seed to ensure RNG is always the same.

In [3]:
import torch

tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

tensor_A,tensor_B,tensor_A==tensor_B

(tensor([[0.6743, 0.0453, 0.1842, 0.2782],
         [0.1744, 0.0551, 0.0784, 0.3398],
         [0.1899, 0.4196, 0.2562, 0.8422]]),
 tensor([[0.6039, 0.5261, 0.8058, 0.4526],
         [0.7623, 0.7152, 0.5767, 0.1711],
         [0.9957, 0.0667, 0.3772, 0.2118]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [6]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3, 4)

tensor_C == tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])